name: Build and Package MontainShooter
on:
  push:
    branches: [main]

jobs:
  build-windows-exe:
    name: Build Windows Executable
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller==6.2.0
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed --name MontainShooter --add-data "assets/*;assets" main.py

      - name: Create deployment package
        run: |
          # Create package structure
          mkdir deploy
          cp dist/MontainShooter.exe deploy/
          cp -r assets deploy/
          
          # Create README file
          echo "MontainShooter - Demo Game" > deploy/README.txt
          echo "Created: $(date)" >> deploy/README.txt
          
          # Zip everything
          7z a -tzip MontainShooter_${{ github.run_number }}.zip ./deploy/*

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: MontainShooter_Windows
          path: MontainShooter_*.zip
