name: Build Windows EXE
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Passo 1: Baixar o código
      - uses: actions/checkout@v4

      # Passo 2: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      # Passo 4: Compilar o executável
      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed --name "MontainShooter" --add-data "assets/*;assets" main.py

      # Passo 5: Upload do artefato (versão atualizada)
      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: MontainShooter
          path: |
            dist/MontainShooter.exe
            assets/
