name: Build MountainShooter
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller==6.2.0
          pip install -r requirements.txt

      - name: Build executable
        run: |
          pyinstaller --onefile --windowed --name MountainShooter --add-data "asset/*;asset" main.py

      - name: Create deployment package
        run: |
          $version = Get-Date -Format "yyyyMMdd-HHmmss"
          Compress-Archive -Path .\dist\MountainShooter.exe, .\asset\* -DestinationPath MountainShooter_$version.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MountainShooter_Package
          path: MountainShooter_*.zip
