name: Build MountainShooter
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install windows-curses==2.3.0
          pip install pyinstaller==6.2.0
          pip install -r requirements.txt

      - name: Verify imports
        run: |
          python -c "import windows_curses; print('windows-curses importado com sucesso')"
          python -c "from main import main; print('Main.py verificado')"

      - name: Build executable
        run: |
          pyinstaller --onefile --windowed ^
            --name MountainShooter ^
            --add-data "asset/*;asset" ^
            --add-data "code/*;code" ^  # Inclui a pasta code
            --hidden-import windows_curses ^
            --hidden-import code.Game ^
            main.py

      - name: Create deployment package
        run: |
          mkdir package
          copy dist\MountainShooter.exe package
          xcopy asset package\asset /E /I
          xcopy code package\code /E /I
          7z a MountainShooter_v%GITHUB_RUN_NUMBER%.zip .\package\*

      - uses: actions/upload-artifact@v4
        with:
          name: MountainShooter_Package
          path: MountainShooter_*.zip
