name: Build MountainShooter
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller==6.2.0
          pip install windows-curses==2.3.0
          pip install -r requirements.txt
          python -c "import sys, windows_curses; print(f'Python {sys.version}\nwindows-curses {windows_curses.__version__} imported successfully')"

      - name: Verify file structure
        run: |
          dir /s /b asset || echo "Warning: asset directory not found"
          dir /s /b code || echo "Warning: code directory not found"
          python -c "import os; print('Current directory:', os.getcwd()); print('Files:', os.listdir('.'))"

      - name: Build executable
        run: |
          pyinstaller ^
            --onefile ^
            --windowed ^
            --name MountainShooter ^
            --add-data "asset/*;asset" ^
            --add-data "code/*;code" ^
            --hidden-import windows_curses ^
            --hidden-import code.Game ^
            --hidden-import code.Menu ^
            main.py

      - name: Verify build
        run: |
          if not exist "dist\MountainShooter.exe" (
            echo "Error: Executable not built!"
            exit /b 1
          )
          echo "Build successful. Executable size:"
          dir /s /b dist

      - name: Package release
        run: |
          mkdir package
          copy dist\MountainShooter.exe package
          xcopy asset package\asset /E /I /Y
          xcopy code package\code /E /I /Y
          7z a MountainShooter_v%GITHUB_RUN_NUMBER%.zip .\package\*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MountainShooter_%GITHUB_RUN_NUMBER%
          path: MountainShooter_*.zip
