name: Build MountainShooter
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd  # Uses Command Prompt instead of PowerShell

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller==6.2.0
          pip install windows-curses==2.3.0
          pip install -r requirements.txt

      - name: Verify assets folder
        run: |
          if not exist "asset" (
            echo Error: Pasta 'asset' não encontrada!
            exit /b 1
          )
          echo Assets encontrados:
          dir /b asset

      - name: Build executable
        run: |
          pyinstaller --onefile --windowed ^
            --name MountainShooter ^
            --add-data "asset/*;asset" ^
            --hidden-import curses ^
            --hidden-import windows-curses ^
            main.py

      - name: Create deployment package
        run: |
          mkdir package
          copy dist\MountainShooter.exe package
          xcopy asset package\asset /E /I
          7z a MountainShooter_v%GITHUB_RUN_NUMBER%.zip .\package\*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MountainShooter_Package
          path: MountainShooter_*.zip
